### ISSUE TITLE
Server is crashing

### ISSUE THREAD

**Issue by sternschnaube** [The-Cat-Town-Craft/Carpet-TCTC-Addition#14]
### Minecraft Version

1.19.3

### Carpet TCTC Addition Version

CarpetTCTCAddition-1.19.3-2.1.173+797db5a-beta

### Description

Using latest Carpet: 1.4.96+v230201
Latest MagicLib: 0.6.213+9c483fd-beta

### To Reproduce

/

### Expected behavior

/

### Log

java.lang.NullPointerException: Cannot invoke "carpet.settings.ParsedRule$FromStringConverter.convert(String)" because "this.converter" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at carpet.settings.ParsedRule.set(ParsedRule.java:285)
	at carpet.api.settings.SettingsManager.loadConfigurationFromConf(SettingsManager.java:419)
	at carpet.api.settings.SettingsManager.attachServer(SettingsManager.java:279)
	at carpet.CarpetServer.lambda$onServerLoaded$2(CarpetServer.java:96)
	at java.util.ArrayList.forEach(ArrayList.java:1511)
	at carpet.CarpetServer.onServerLoaded(CarpetServer.java:94)
	at net.minecraft.server.MinecraftServer.handler$zjh000$serverLoaded(MinecraftServer:5309)
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer)
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.setupServer(MinecraftDedicatedServer:169)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:648)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:264)
	at java.lang.Thread.run(Thread.java:833)

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
Try using MagicLib [0.6.216+0346369](https://github.com/Hendrix-Shen/MagicLib/releases/tag/dev%2F0.6.216).

**Comment by venaminecraft** [comment]
Works, thank you!! 😊
