### ISSUE TITLE
[Bug] rule UpdateSuppression in origin carpet sometimes doesn't work when rule UpdateSuppression is set to false in carpet TCTC

### ISSUE THREAD

**Issue by Arthur-Montgomery** [The-Cat-Town-Craft/Carpet-TCTC-Addition#17]
### Minecraft Version

1.17.1

### Carpet TCTC Addition Version

CarpetTCTCAddition-1.17.1-2.2.198+127ab0a-stable

### Description

When rule UpdateSuppression in origin carpet set to true
rule UpdateSuppression in carpet TCTC set to false
game sometimes doesn't prevent crashing caused by non-player activated updatesupression

### To Reproduce

enter world with carpet and carpet TCTC
set UpdateSuppression in carpet TCTC to false
paste an updatesuppressor and make it work( I used gpw version)
put a random block on a piston in the BUD line
game crashes

### Expected behavior

after doing above, carpet should prevent crashing.
When I retried this with only carpet, it perfectly prevented the game from crashing.

### Log
```
[16:03:15] [Server thread/INFO]: ArthurMontgomery加入了游戏
[16:03:15] [Render thread/INFO]: Started 2 worker threads
[16:03:15] [Render thread/INFO]: Using 3 total BufferBuilder caches
[16:03:15] [Server thread/INFO]: Saving and pausing game...
[16:03:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:overworld
[16:03:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_nether
[16:03:15] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_end
[16:03:16] [Render thread/INFO]: Loaded 91 advancements
[16:03:27] [Server thread/INFO]: [ArthurMontgomery: 目前启用的 Carpet Mod 选项:]
[16:03:27] [Server thread/INFO]: [ArthurMontgomery: - 创造玩家无碰撞检测 (creativeNoClip) [true] [false]]
[16:03:27] [Server thread/INFO]: [ArthurMontgomery: - 语言 (language) [none] [zh_cn] [zh_tw]]
[16:03:27] [Server thread/INFO]: [ArthurMontgomery: Carpet Mod 版本: 1.4.57+v220119]
[16:03:27] [Server thread/INFO]: [ArthurMontgomery: MagicLib version: 0.7.336+05361cf-stable (Public Release) ]
[16:03:27] [Server thread/INFO]: [ArthurMontgomery: CarpetTCTCAddition version: 2.2.198+127ab0a-stable (Public Release) ]
[16:03:27] [Server thread/INFO]: [ArthurMontgomery: 浏览分类:
[发射器] [特性] [优化] [Scarpet脚本语言] [生存] [客户端] [extras] [试验性] [TNT] [漏洞修复] [指令] [创造]]
[16:03:27] [Render thread/INFO]: [CHAT] 目前启用的 Carpet Mod 选项:
[16:03:27] [Render thread/INFO]: [CHAT] - 创造玩家无碰撞检测 (creativeNoClip) [true] [false]
[16:03:27] [Render thread/INFO]: [CHAT] - 语言 (language) [none] [zh_cn] [zh_tw]
[16:03:27] [Render thread/INFO]: [CHAT] Carpet Mod 版本: 1.4.57+v220119
[16:03:27] [Render thread/INFO]: [CHAT] MagicLib version: 0.7.336+05361cf-stable (Public Release) 
[16:03:27] [Render thread/INFO]: [CHAT] CarpetTCTCAddition version: 2.2.198+127ab0a-stable (Public Release) 
[16:03:27] [Render thread/INFO]: [CHAT] 浏览分类:\n[发射器] [特性] [优化] [Scarpet脚本语言] [生存] [客户端] [extras] [试验性] [TNT] [漏洞修复] [指令] [创造]
[16:03:34] [Server thread/INFO]: [ArthurMontgomery: Current CarpetTCTCAddition settings: ]
[16:03:34] [Server thread/INFO]: [ArthurMontgomery: - updateSuppressionCrashFix [true] [false]]
[16:03:34] [Server thread/INFO]: [ArthurMontgomery: MagicLib version: 0.7.336+05361cf-stable (Public Release) ]
[16:03:34] [Server thread/INFO]: [ArthurMontgomery: CarpetTCTCAddition version: 2.2.198+127ab0a-stable (Public Release) ]
[16:03:34] [Server thread/INFO]: [ArthurMontgomery: Browse categories:]
[16:03:34] [Server thread/INFO]: [ArthurMontgomery: Tags: [Bugfix] [Client] [Command] [Experimental] [feature] [Misc] [Protocol] [WorldGenerate]]
[16:03:34] [Render thread/INFO]: [CHAT] Current CarpetTCTCAddition settings: 
[16:03:34] [Render thread/INFO]: [CHAT] - updateSuppressionCrashFix [true] [false]
[16:03:34] [Render thread/INFO]: [CHAT] MagicLib version: 0.7.336+05361cf-stable (Public Release) 
[16:03:34] [Render thread/INFO]: [CHAT] CarpetTCTCAddition version: 2.2.198+127ab0a-stable (Public Release) 
[16:03:34] [Render thread/INFO]: [CHAT] Browse categories:
[16:03:34] [Render thread/INFO]: [CHAT] Tags: [Bugfix] [Client] [Command] [Experimental] [feature] [Misc] [Protocol] [WorldGenerate]
[16:03:37] [Server thread/INFO]: [ArthurMontgomery: updateSuppressionCrashFix: false, [Change permanently?]]
[16:03:37] [Render thread/INFO]: [CHAT] updateSuppressionCrashFix: false, [Change permanently?]
[16:03:40] [Server thread/INFO]: [ArthurMontgomery: Rule updateSuppressionCrashFix will now default to false.]
[16:03:40] [Render thread/INFO]: [CHAT] Rule updateSuppressionCrashFix will now default to false.
[16:03:49] [Server thread/INFO]: [ArthurMontgomery: updateSuppressionCrashFix: true, [永久更改?]]
[16:03:49] [Render thread/INFO]: [CHAT] updateSuppressionCrashFix: true, [永久更改?]
[16:03:51] [Server thread/INFO]: [ArthurMontgomery: 规则“updateSuppressionCrashFix”将会被默认设置为true]
[16:03:51] [Render thread/INFO]: [CHAT] 规则“updateSuppressionCrashFix”将会被默认设置为true
[16:04:01] [Server thread/INFO]: We caught an update suppression exception. This should cause the server to crash, but we prevented it.
[16:04:02] [Server thread/INFO]: We caught an update suppression exception. This should cause the server to crash, but we prevented it.
[16:04:02] [Render thread/INFO]: [CHAT] We caught an update suppression exception. This should cause the server to crash, but we prevented it.
[16:04:02] [Render thread/INFO]: [CHAT] We caught an update suppression exception. This should cause the server to crash, but we prevented it.
[16:04:11] [Server thread/FATAL]: Error executing task on Server
carpet.helpers.ThrowableSuppression: Update suppression
	at net.minecraft.class_1937.handler$zie000$checkUpdateSuppression(class_1937.java:4072) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8492(class_1937.java:358) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8452(class_1937.java:321) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_8408(class_3218.java:1307) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.redirect$zzj000$updateNeighborsMaybe(class_1937.java:1573) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:235) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_30093(class_1937.java:298) ~[client-intermediary.jar:?]
	at net.minecraft.class_2248.method_9611(class_2248.java:160) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26183(class_4970.java:897) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:245) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8652(class_1937.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8650(class_1937.java:271) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:249) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_21717(class_3225.java:221) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java:154) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:1012) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbe000$modifiedRunLoop(MinecraftServer.java:2899) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[16:04:27] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception while ticking
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:895) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:96) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbe000$modifiedRunLoop(MinecraftServer.java:2890) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: carpet.helpers.ThrowableSuppression: Update suppression
	at net.minecraft.class_1937.handler$zie000$checkUpdateSuppression(class_1937.java:4072) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8492(class_1937.java:358) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8508(class_1937.java:342) ~[client-intermediary.jar:?]
	at net.minecraft.class_2426.method_10365(class_2426.java:73) ~[client-intermediary.jar:?]
	at net.minecraft.class_2426.method_9588(class_2426.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:918) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_14189(class_3218.java:644) ~[client-intermediary.jar:?]
	at me.jellysquid.mods.lithium.common.world.scheduler.LithiumServerTickScheduler.executeTicks(LithiumServerTickScheduler.java:280) ~[lithium-fabric-mc1.17.1-0.7.5.jar:?]
	at me.jellysquid.mods.lithium.common.world.scheduler.LithiumServerTickScheduler.method_8670(LithiumServerTickScheduler.java:93) ~[lithium-fabric-mc1.17.1-0.7.5.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:364) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tctc$onTickingWorld(MinecraftServer.java:7296) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891) ~[client-intermediary.jar:?]
	... 6 more
[16:04:28] [Server thread/ERROR]: This crash report has been saved to: D:\.minecraft\versions\1.17.1\crash-reports\crash-2023-06-19_16.04.27-server.txt
[16:04:28] [Server thread/INFO]: Stopping server
[16:04:28] [Server thread/INFO]: Saving players
[16:04:28] [Server thread/INFO]: ArthurMontgomery lost connection: 连接中止
[16:04:28] [Server thread/INFO]: ArthurMontgomery退出了游戏
[16:04:28] [Server thread/INFO]: Stopping singleplayer server as player logged out
[16:04:28] [Server thread/INFO]: Saving worlds
[16:04:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:overworld
[16:04:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_nether
[16:04:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_end
[16:04:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (新的世界): All chunks are saved
[16:04:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[16:04:29] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[16:04:29] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
```

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Arthur-Montgomery** [comment]
carpet version: fabric-carpet-1.17.1-1.4.57+v220119

**Comment by Jog-Ming** [comment]
I do think this is intended as a feature(?) The carpet TCTC addition rule should override the original rule.

**Comment by Jog-Ming** [comment]
I think this is no longer an issue in the latest version of carpet TCTC addition.
