### ISSUE TITLE
No sub commands from Carpet showing.

### ISSUE THREAD

**Issue by Aculoss** [The-Cat-Town-Craft/Carpet-TCTC-Addition#6]
When i type /here, it isnt possible. TCTC is loaded in mods and i have magiclib but your exp/2.0 version for 1.19 does not do anything. No errors in log and TCTC is definately loaded when i type mods or look in console. Also /carpettctcaddition is not an option even if im OP.

**Comment by Hendrix-Shen** [comment]
[2.0.160+79d49e9](https://github.com/The-Cat-Town-Craft/Carpet-TCTC-Addition/suites/7131198462/artifacts/283135121) should be working properly. However, it is still in the testing phase and unpredictable errors are likely to occur.

**Comment by Aculoss** [comment]
It is the one in the libs folder? Like when built with Gradle and not the tmp?

**Comment by Aculoss** [comment]
[17:53:17] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[17:53:18] [main/INFO]: Loading 145 mods:
	- adventure-platform-fabric 5.4.0-SNAPSHOT via floodgate
	- anvil-crush 1.6.1
	- baritone 1.9.0-local
	- c2me 0.2.0+alpha.8.2
	- c2me-base 0.2.0+alpha.8.2 via c2me
	- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.8.2 via c2me
	- c2me-fixes-general-threading-issues 0.2.0+alpha.8.2 via c2me
	- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.8.2 via c2me
	- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.8.2 via c2me
	- c2me-notickvd 0.2.0+alpha.8.2 via c2me
	- c2me-opts-allocs 0.2.0+alpha.8.2 via c2me
	- c2me-opts-chunk-access 0.2.0+alpha.8.2 via c2me
	- c2me-opts-chunkio 0.2.0+alpha.8.2 via c2me
	- c2me-opts-math 0.2.0+alpha.8.2 via c2me
	- c2me-opts-scheduling 0.2.0+alpha.8.2 via c2me
	- c2me-opts-worldgen-general 0.2.0+alpha.8.2 via c2me
	- c2me-opts-worldgen-vanilla 0.2.0+alpha.8.2 via c2me
	- c2me-rewrites-chunkio 0.2.0+alpha.8.2 via c2me
	- c2me-server-utils 0.2.0+alpha.8.2 via c2me
	- c2me-threading-chunkio 0.2.0+alpha.8.2 via c2me
	- c2me-threading-lighting 0.2.0+alpha.8.2 via c2me
	- c2me-threading-scheduling 0.2.0+alpha.8.2 via c2me
	- c2me-threading-worldgen 0.2.0+alpha.8.2 via c2me
	- cardinal-components-base 5.0.0-beta.1 via fabrichomes
	- cardinal-components-entity 5.0.0-beta.1 via fabrichomes
	- cardinal-components-world 5.0.0-beta.1 via fabricwarps
	- carpet 1.4.79
	- carpet-autocraftingtable 1.4.57
	- carpet-extra 1.4.79
	- carpet-fixes 1.19-1.9.2
	- carpet-tctc-addition 2.0.160+79d49e9-beta
	- carpet-tctc-addition-1_19 2.0.160+79d49e9-beta via carpet-tctc-addition
	- carpet-tis-addition 1.37.0
	- carpetgamerules 1.2.1
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 7.0.72
	- cloud 1.7.0-SNAPSHOT via floodgate
	- cloud_commandframework_cloud-brigadier_ 1.7.0-SNAPSHOT via cloud
	- cloud_commandframework_cloud-core_ 1.7.0-SNAPSHOT via cloud
	- cloud_commandframework_cloud-services_ 1.7.0-SNAPSHOT via cloud
	- com_electronwill_night-config_core 3.6.5 via c2me
	- com_electronwill_night-config_toml 3.6.5 via c2me
	- com_github_llamalad7_mixinextras 0.0.6 via carpet-fixes
	- com_ibm_async_asyncutil 0.1.0 via c2me
	- com_moandjiezana_toml_toml4j 0.7.2 via jline4mcdsrv
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- conditional-mixin 0.3.0 via carpet-fixes
	- essentialaddons 1.19-1.1.3
	- fabric 0.57.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via fabric
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.27+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.0+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.1+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.4+767db26ea9 via fabric
	- fabric-item-groups-v0 0.3.25+9ff28f40a9 via fabric
	- fabric-language-kotlin 1.7.2+kotlin.1.6.20
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
	- fabric-loot-api-v2 1.1.0+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.3+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.10+33fbc738a9 via fabric
	- fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
	- fabric-networking-v0 0.3.14+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.7+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via fabric-tpa
	- fabric-registry-sync-v0 0.9.17+23c4cfefa9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.5+a6d2f785a9 via fabric
	- fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
	- fabric-tpa 3.2.1
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabrichomes 2.3.0
	- fabricloader 0.14.8
	- fabricwarps 2.3.0
	- ferritecore 4.2.1
	- floodgate 2.2.0-SNAPSHOT
	- geyser-fabric 2.0.4-SNAPSHOT
	- hopperspeedsim 1.0
	- io_leangen_geantyref_geantyref 1.3.13 via cloud
	- itemflexer 1.2.5
	- ivan-carpet-addition 2.1.1
	- java 17
	- jline4mcdsrv 0.3.0
	- krypton 0.2.0
	- lazydfu 0.1.3
	- lithium 0.8.1-SNAPSHOT
	- magiclib 0.5.32
	- magiclib-1_19 0.5.32 via magiclib
	- microconfig 2.2.1 via itemflexer
	- minecraft 1.19
	- minitweaks 1.19-1.3.1
	- more_codecs 0.2.2+1.18 via player_roles
	- net_kyori_adventure-api 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-key 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-platform-api 4.1.0 via adventure-platform-fabric
	- net_kyori_adventure-text-logger-slf4j 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-minimessage 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-gson 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-plain 4.11.0 via adventure-platform-fabric
	- net_kyori_examination-api 1.3.0 via adventure-platform-fabric
	- net_kyori_examination-string 1.3.0 via adventure-platform-fabric
	- org_fusesource_jansi_jansi 2.4.0 via jline4mcdsrv
	- org_jetbrains_kotlin_kotlin-reflect 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_jline_jline 3.21.0 via jline4mcdsrv
	- org_jline_jline-terminal-jansi 3.21.0 via jline4mcdsrv
	- org_threadly_threadly 7.0 via c2me
	- org_yaml_snakeyaml 1.30 via carpet-tis-addition
	- pca 0.2.5-beta+1703874
	- perfectaccuracy 1.2-1.19
	- phosphor 0.8.1
	- placeholder-api 2.0.0-beta.5+1.19 via itemflexer
	- player_roles 1.6.0
	- player_roles_api 1.6.0 via player_roles
	- pvptoggle 1.0.6
	- recipecache 0.2.0-1.19
	- rug 1.19-1.3.3
	- servshred 1.0.8
	- sgui 1.1.1+1.19 via rug
	- totos-carpet-tweaks 0.2.5
	- worldedit 7.2.11-beta-01+6200-0877589
	- xpbeacons 7.1
[17:53:19] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/jbake/Desktop/J/Minecraft/Aculos'%20Survival/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[17:53:19] [main/INFO]: Compatibility level set to JAVA_17
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.base.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.fixes.chunkio.threading_issues.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.fixes.general.threading_issues.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.threading_issues.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.fixes.worldgen.vanilla_bugs.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.notickvd.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.opts.allocs.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.opts.chunk_access.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.opts.chunkio.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.opts.math.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.opts.scheduling.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.general.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.opts.worldgen.vanilla.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.rewrites.chunkio.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.server.utils.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.threading.chunkio.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.threading.lighting.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.threading.scheduling.mixin
[17:53:20] [main/INFO]: Initializing com.ishland.c2me.threading.worldgen.mixin
[17:53:20] [main/INFO]: Disabling com.ishland.c2me.threading.worldgen.mixin
[17:53:21] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 2 override(s) found
[17:53:24] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[17:53:24] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [c2me, krypton]) disables it and children
[17:53:24] [main/WARN]: [carpet] detected, disabling UPDATE mixin com.sk89q.worldedit.fabric.mixin.MixinLevelChunkSetBlockHook
[17:53:28] [main/WARN]: Method overwrite conflict for getLanguage in worldedit-fabric.mixins.json:MixinServerPlayer from mod worldedit, previously written by carpet.mixins.ServerPlayer_scarpetEventMixin. Skipping method.
[17:53:28] [main/WARN]: @Redirect conflict. Skipping carpet-tctc-addition.mixins.json:rule.enderPlatform.MixinServerPlayer from mod carpet-tctc-addition-1_19->@Redirect::makeObsidianPlatform(Lnet/minecraft/class_3222;Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;)V with priority 1000, already redirected by carpet-fixes.mixins.json:playerFixes.ServerPlayerEntity_spawnPlatformMixin from mod carpet-fixes->@Redirect::dontRecreateObsidianPlatform(Lnet/minecraft/class_3222;Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;)V with priority 1000
[17:53:28] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.handler$zon000$gameStarted(class_128.java:515) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:91) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 3 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at carpet_autocraftingtable.AutoCraftingTable.<clinit>(AutoCraftingTable.java:10) ~[carpet-autocraftingtable-1.19-1.4.57.jar:?]
	at net.minecraft.class_128.handler$zon000$gameStarted(class_128.java:515) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:91) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at carpet_autocraftingtable.AutoCraftingTable.<clinit>(AutoCraftingTable.java:10) ~[carpet-autocraftingtable-1.19-1.4.57.jar:?]
	at net.minecraft.class_128.handler$zon000$gameStarted(class_128.java:515) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:91) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 3 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector makeObsidianPlatform(Lnet/minecraft/class_3222;Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;)V in carpet-tctc-addition.mixins.json:rule.enderPlatform.MixinServerPlayer from mod carpet-tctc-addition-1_19 failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap CarpetTCTCAddition-1.19-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at carpet_autocraftingtable.AutoCraftingTable.<clinit>(AutoCraftingTable.java:10) ~[carpet-autocraftingtable-1.19-1.4.57.jar:?]
	at net.minecraft.class_128.handler$zon000$gameStarted(class_128.java:515) ~[server-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java) ~[server-intermediary.jar:?]
	at net.minecraft.server.Main.main(Main.java:91) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 3 more

**Comment by Aculoss** [comment]
Found its a conflict with the End Platform from the mod Carpet Fixes

**Comment by Hendrix-Shen** [comment]
This is a known issue that currently conflicts with Carpet Fixes and will need to wait for a solution. Duplicate with https://github.com/The-Cat-Town-Craft/Carpet-TCTC-Addition/issues/5#issuecomment-1166615070

**Comment by Hendrix-Shen** [comment]
Redirection conflicts are often difficult to resolve. It will take me a while to work on these issues.
