### ISSUE TITLE
[Bug] [1.18.2] crash with carpet fixes 1.18.x-1.7.11

### ISSUE THREAD

**Issue by DadoIrie** [The-Cat-Town-Craft/Carpet-TCTC-Addition#8]
### Minecraft Version

1.18.2

### Carpet TCTC Addition Version

2.0.176

### Description

crashes on launch with the latest version of carpet fixes (which is 1.18.x-1.7.11)

### To Reproduce

launch mc with tctc and carpet fixes

### Expected behavior

not crashing :)

### Log

Mods:
  [✔️] carpet-fixes-1.18.x-1.7.11
  [✔️] CarpetTCTCAddition-2.0.176+d80e88f-beta
  [✔️] fabric-api-0.58.0+1.18.2
  [✔️] fabric-carpet-1.18.2-1.4.69+v220331
  [✔️] magiclib-0.5.32
  [✔️] malilib-fabric-1.18.2-0.12.1

Params:
  --username  --version 1.18.2 --gameDir C:/Users/Dado/AppData/Roaming/PolyMC/instances/WIP unnamed 1.18.2 Fabric TCTC TEST/.minecraft --assetsDir C:/Users/Dado/AppData/Roaming/PolyMC/assets --assetIndex 1.18 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx10240m, -Duser.language=en]

Minecraft process ID: 17740

[22:25:00] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.8
[22:25:00] [ForkJoinPool-1-worker-2/WARN]: Mod carpet-fixes uses the version 1.18.x-1.7.11 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'x'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[22:25:00] [main/INFO]: Loading 57 mods:
	- carpet 1.4.69
	- carpet-fixes 1.18.x-1.7.11
	- carpet-tctc-addition 2.0.176+d80e88f-beta
	- carpet-tctc-addition-1_18_2 2.0.176+d80e88f-beta via carpet-tctc-addition
	- com_github_llamalad7_mixinextras 0.0.6 via carpet-fixes
	- conditional-mixin 0.3.1 via carpet-fixes
	- fabric 0.58.0+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.2+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.6+651bcc5960 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.23+d7c144a860 via fabric
	- fabric-content-registries-v0 3.1.1+c85f2e3860 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.2.1+ee261a3e60 via fabric
	- fabric-data-generation-api-v1 3.0.1+9fcb91d260 via fabric
	- fabric-dimensions-v1 2.1.20+489d6f8260 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.19+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.5.2+17cbbd4360 via fabric
	- fabric-item-groups-v0 0.3.14+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.1.0+cc71601c60 via fabric
	- fabric-loot-api-v2 1.1.0+1997ad1260 via fabric
	- fabric-loot-tables-v1 1.1.2+e747827960 via fabric
	- fabric-mining-level-api-v1 2.1.4+cc71601c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.23+2d30af4b60 via fabric
	- fabric-networking-v0 0.3.10+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.3+032c981d60 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.10+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.3+41a02c8a60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.5.2+446e059560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.2+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.3+f4563ac860 via fabric
	- fabric-transitive-access-wideners-v1 1.1.0+e747827960 via fabric
	- fabricloader 0.14.8
	- java 18
	- magiclib 0.5.32
	- magiclib-1_18_2 0.5.32 via magiclib
	- malilib 0.12.1
	- minecraft 1.18.2
[22:25:00] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Dado/AppData/Roaming/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[22:25:00] [main/INFO]: Compatibility level set to JAVA_16
[22:25:00] [main/INFO]: Compatibility level set to JAVA_17
[22:25:02] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[22:25:02] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[22:25:03] [main/WARN]: @Redirect conflict. Skipping carpet-tctc-addition.mixins.json:rule.enderPlatform.MixinServerPlayer from mod carpet-tctc-addition-1_18_2->@Redirect::makeObsidianPlatform(Lnet/minecraft/class_3222;Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;)V with priority 1000, already redirected by carpet-fixes.mixins.json:playerFixes.ServerPlayerEntity_spawnPlatformMixin from mod carpet-fixes->@Redirect::dontRecreateObsidianPlatform(Lnet/minecraft/class_3222;Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;)V with priority 1000
[22:25:03] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3222 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.class_6396.handler$zhl000$fillSystemDetails(class_6396.java:521) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[minecraft-1.18.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 9 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.class_6396.handler$zhl000$fillSystemDetails(class_6396.java:521) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[minecraft-1.18.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 9 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector makeObsidianPlatform(Lnet/minecraft/class_3222;Lnet/minecraft/class_3218;Lnet/minecraft/class_2338;)V in carpet-tctc-addition.mixins.json:rule.enderPlatform.MixinServerPlayer from mod carpet-tctc-addition-1_18_2 failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap CarpetTCTCAddition-1.18.2-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.minecraft.class_6396.handler$zhl000$fillSystemDetails(class_6396.java:521) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.<init>(class_6396.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[minecraft-1.18.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.8.jar:?]
	... 9 more
Process exited with code 1.

### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
Phase with #7.

**Comment by Hendrix-Shen** [comment]
I noticed this problem because FX did not follow the semantic version numbering rules, resulting in the compat module not working properly. If possible I hope FX doesn't change the version numbering rules again, otherwise it will break everything again.

**Comment by Hendrix-Shen** [comment]
Try this version [2.0.177+d21bda9](https://github.com/The-Cat-Town-Craft/Carpet-TCTC-Addition/releases/tag/dev-177).
